hive:  
  url: jdbc:hive2://172.16.0.10:10000/default
  driver-class-name: org.apache.hive.jdbc.HiveDriver 
  type: com.alibaba.druid.pool.DruidDataSource
  username: hive
  password: hive
spring:
  cloud:
    stream:
      bindings:
        input-topic:
          group: input-consumer-1
          destination: customer.topic.test
      kafka:
        binder:
          brokers: localhost:9092
          configuration:
            key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value.deserializer: com.learning.springbasickafka.serializer.CustomerDeserializer
            
