/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.kafka.learning.basickafkaprograms.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Event extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Event\",\"namespace\":\"com.kafka.learning.basickafkaprograms.avro\",\"fields\":[{\"name\":\"eventId\",\"type\":\"long\"},{\"name\":\"eventName\",\"type\":\"string\",\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public long eventId;
  @Deprecated public java.lang.CharSequence eventName;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Event() {}

  /**
   * All-args constructor.
   */
  public Event(java.lang.Long eventId, java.lang.CharSequence eventName) {
    this.eventId = eventId;
    this.eventName = eventName;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return eventId;
    case 1: return eventName;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: eventId = (java.lang.Long)value$; break;
    case 1: eventName = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'eventId' field.
   */
  public java.lang.Long getEventId() {
    return eventId;
  }

  /**
   * Sets the value of the 'eventId' field.
   * @param value the value to set.
   */
  public void setEventId(java.lang.Long value) {
    this.eventId = value;
  }

  /**
   * Gets the value of the 'eventName' field.
   */
  public java.lang.CharSequence getEventName() {
    return eventName;
  }

  /**
   * Sets the value of the 'eventName' field.
   * @param value the value to set.
   */
  public void setEventName(java.lang.CharSequence value) {
    this.eventName = value;
  }

  /** Creates a new Event RecordBuilder */
  public static com.kafka.learning.basickafkaprograms.avro.Event.Builder newBuilder() {
    return new com.kafka.learning.basickafkaprograms.avro.Event.Builder();
  }
  
  /** Creates a new Event RecordBuilder by copying an existing Builder */
  public static com.kafka.learning.basickafkaprograms.avro.Event.Builder newBuilder(com.kafka.learning.basickafkaprograms.avro.Event.Builder other) {
    return new com.kafka.learning.basickafkaprograms.avro.Event.Builder(other);
  }
  
  /** Creates a new Event RecordBuilder by copying an existing Event instance */
  public static com.kafka.learning.basickafkaprograms.avro.Event.Builder newBuilder(com.kafka.learning.basickafkaprograms.avro.Event other) {
    return new com.kafka.learning.basickafkaprograms.avro.Event.Builder(other);
  }
  
  /**
   * RecordBuilder for Event instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Event>
    implements org.apache.avro.data.RecordBuilder<Event> {

    private long eventId;
    private java.lang.CharSequence eventName;

    /** Creates a new Builder */
    private Builder() {
      super(com.kafka.learning.basickafkaprograms.avro.Event.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.kafka.learning.basickafkaprograms.avro.Event.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.eventId)) {
        this.eventId = data().deepCopy(fields()[0].schema(), other.eventId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.eventName)) {
        this.eventName = data().deepCopy(fields()[1].schema(), other.eventName);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Event instance */
    private Builder(com.kafka.learning.basickafkaprograms.avro.Event other) {
            super(com.kafka.learning.basickafkaprograms.avro.Event.SCHEMA$);
      if (isValidValue(fields()[0], other.eventId)) {
        this.eventId = data().deepCopy(fields()[0].schema(), other.eventId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.eventName)) {
        this.eventName = data().deepCopy(fields()[1].schema(), other.eventName);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'eventId' field */
    public java.lang.Long getEventId() {
      return eventId;
    }
    
    /** Sets the value of the 'eventId' field */
    public com.kafka.learning.basickafkaprograms.avro.Event.Builder setEventId(long value) {
      validate(fields()[0], value);
      this.eventId = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'eventId' field has been set */
    public boolean hasEventId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'eventId' field */
    public com.kafka.learning.basickafkaprograms.avro.Event.Builder clearEventId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'eventName' field */
    public java.lang.CharSequence getEventName() {
      return eventName;
    }
    
    /** Sets the value of the 'eventName' field */
    public com.kafka.learning.basickafkaprograms.avro.Event.Builder setEventName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.eventName = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'eventName' field has been set */
    public boolean hasEventName() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'eventName' field */
    public com.kafka.learning.basickafkaprograms.avro.Event.Builder clearEventName() {
      eventName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public Event build() {
      try {
        Event record = new Event();
        record.eventId = fieldSetFlags()[0] ? this.eventId : (java.lang.Long) defaultValue(fields()[0]);
        record.eventName = fieldSetFlags()[1] ? this.eventName : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
