/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.kafka.learning.basickafkaprograms.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Student extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Student\",\"namespace\":\"com.kafka.learning.basickafkaprograms.avro\",\"fields\":[{\"name\":\"studentId\",\"type\":\"long\"},{\"name\":\"studentName\",\"type\":\"string\"},{\"name\":\"studentGender\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public long studentId;
  @Deprecated public java.lang.CharSequence studentName;
  @Deprecated public java.lang.CharSequence studentGender;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Student() {}

  /**
   * All-args constructor.
   */
  public Student(java.lang.Long studentId, java.lang.CharSequence studentName, java.lang.CharSequence studentGender) {
    this.studentId = studentId;
    this.studentName = studentName;
    this.studentGender = studentGender;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return studentId;
    case 1: return studentName;
    case 2: return studentGender;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: studentId = (java.lang.Long)value$; break;
    case 1: studentName = (java.lang.CharSequence)value$; break;
    case 2: studentGender = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'studentId' field.
   */
  public java.lang.Long getStudentId() {
    return studentId;
  }

  /**
   * Sets the value of the 'studentId' field.
   * @param value the value to set.
   */
  public void setStudentId(java.lang.Long value) {
    this.studentId = value;
  }

  /**
   * Gets the value of the 'studentName' field.
   */
  public java.lang.CharSequence getStudentName() {
    return studentName;
  }

  /**
   * Sets the value of the 'studentName' field.
   * @param value the value to set.
   */
  public void setStudentName(java.lang.CharSequence value) {
    this.studentName = value;
  }

  /**
   * Gets the value of the 'studentGender' field.
   */
  public java.lang.CharSequence getStudentGender() {
    return studentGender;
  }

  /**
   * Sets the value of the 'studentGender' field.
   * @param value the value to set.
   */
  public void setStudentGender(java.lang.CharSequence value) {
    this.studentGender = value;
  }

  /** Creates a new Student RecordBuilder */
  public static com.kafka.learning.basickafkaprograms.avro.Student.Builder newBuilder() {
    return new com.kafka.learning.basickafkaprograms.avro.Student.Builder();
  }
  
  /** Creates a new Student RecordBuilder by copying an existing Builder */
  public static com.kafka.learning.basickafkaprograms.avro.Student.Builder newBuilder(com.kafka.learning.basickafkaprograms.avro.Student.Builder other) {
    return new com.kafka.learning.basickafkaprograms.avro.Student.Builder(other);
  }
  
  /** Creates a new Student RecordBuilder by copying an existing Student instance */
  public static com.kafka.learning.basickafkaprograms.avro.Student.Builder newBuilder(com.kafka.learning.basickafkaprograms.avro.Student other) {
    return new com.kafka.learning.basickafkaprograms.avro.Student.Builder(other);
  }
  
  /**
   * RecordBuilder for Student instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Student>
    implements org.apache.avro.data.RecordBuilder<Student> {

    private long studentId;
    private java.lang.CharSequence studentName;
    private java.lang.CharSequence studentGender;

    /** Creates a new Builder */
    private Builder() {
      super(com.kafka.learning.basickafkaprograms.avro.Student.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.kafka.learning.basickafkaprograms.avro.Student.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.studentId)) {
        this.studentId = data().deepCopy(fields()[0].schema(), other.studentId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.studentName)) {
        this.studentName = data().deepCopy(fields()[1].schema(), other.studentName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.studentGender)) {
        this.studentGender = data().deepCopy(fields()[2].schema(), other.studentGender);
        fieldSetFlags()[2] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Student instance */
    private Builder(com.kafka.learning.basickafkaprograms.avro.Student other) {
            super(com.kafka.learning.basickafkaprograms.avro.Student.SCHEMA$);
      if (isValidValue(fields()[0], other.studentId)) {
        this.studentId = data().deepCopy(fields()[0].schema(), other.studentId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.studentName)) {
        this.studentName = data().deepCopy(fields()[1].schema(), other.studentName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.studentGender)) {
        this.studentGender = data().deepCopy(fields()[2].schema(), other.studentGender);
        fieldSetFlags()[2] = true;
      }
    }

    /** Gets the value of the 'studentId' field */
    public java.lang.Long getStudentId() {
      return studentId;
    }
    
    /** Sets the value of the 'studentId' field */
    public com.kafka.learning.basickafkaprograms.avro.Student.Builder setStudentId(long value) {
      validate(fields()[0], value);
      this.studentId = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'studentId' field has been set */
    public boolean hasStudentId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'studentId' field */
    public com.kafka.learning.basickafkaprograms.avro.Student.Builder clearStudentId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'studentName' field */
    public java.lang.CharSequence getStudentName() {
      return studentName;
    }
    
    /** Sets the value of the 'studentName' field */
    public com.kafka.learning.basickafkaprograms.avro.Student.Builder setStudentName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.studentName = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'studentName' field has been set */
    public boolean hasStudentName() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'studentName' field */
    public com.kafka.learning.basickafkaprograms.avro.Student.Builder clearStudentName() {
      studentName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'studentGender' field */
    public java.lang.CharSequence getStudentGender() {
      return studentGender;
    }
    
    /** Sets the value of the 'studentGender' field */
    public com.kafka.learning.basickafkaprograms.avro.Student.Builder setStudentGender(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.studentGender = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'studentGender' field has been set */
    public boolean hasStudentGender() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'studentGender' field */
    public com.kafka.learning.basickafkaprograms.avro.Student.Builder clearStudentGender() {
      studentGender = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public Student build() {
      try {
        Student record = new Student();
        record.studentId = fieldSetFlags()[0] ? this.studentId : (java.lang.Long) defaultValue(fields()[0]);
        record.studentName = fieldSetFlags()[1] ? this.studentName : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.studentGender = fieldSetFlags()[2] ? this.studentGender : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
